In [1]:
import numpy as np

In [2]:
#input layer
class inputLayer:

    def __init__(self, number_of_input): 
        self.number_of_input = number_of_input
    
    #to add the vlaues in the network 
    def use(self, input_matrix):
        if isinstance(input_matrix,np.ndarray):
            self.out_matrix = input_matrix
            return input_matrix
        else:
            self.out_matrix = np.array(input_matrix)
            return self.out_matrix
    
    def fetchInputValues(self):
        return self.out_matrix

#hidden and output layers
class layers:
    
    def __init__(self, number_of_input, number_of_neurons, activation='relu'):
        low, high = -1, 1
        self.weight_matrix = np.random.uniform(low, high, size=(number_of_input, number_of_neurons))
        self.bias = np.random.uniform(low, high, size=(1, number_of_neurons))
        self.activation = activation

    def apply_activation(self, values):
        if self.activation == 'relu':
            return np.maximum(0, values)
        elif self.activation == 'sigmoid':
            return 1 / (1 + np.exp(-values))
        elif self.activation == 'tanh':
            return np.tanh(values)
        elif self.activation == 'softmax':
            e_x = np.exp(values - np.max(values, axis=-1, keepdims=True))
            return e_x / np.sum(e_x, axis=-1, keepdims=True)
        else:
            return values  # No activation (identity)

    def compute_derivative(self, values):
        if self.activation == 'relu':
            return (values > 0).astype(float)
        elif self.activation == 'sigmoid':
            sigmoid_output = self.apply_activation(values)
            return sigmoid_output * (1 - sigmoid_output)
        elif self.activation == 'tanh':
            tanh_output = self.apply_activation(values)
            return 1 - tanh_output**2
        elif self.activation == 'softmax':
            softmax_output = self.apply_activation(values)
            return softmax_output * (1 - softmax_output)  # Note: This derivative might not be used often for softmax
        else:
            return np.ones_like(values)  # Derivative of the identity function is 1

    def forward(self, input_matrix):
        values = np.dot(input_matrix, self.weight_matrix) + self.bias
        return self.apply_activation(values)
    


In [ ]:
class layersT:
    
    def __init__(self, number_of_input, number_of_neurons, activation='relu', wig , bia):
        low, high = -1, 1
        self.weight_matrix = wig
        self.bias = bia
        self.activation = activation

    def apply_activation(self, values):
        if self.activation == 'relu':
            return np.maximum(0, values)
        elif self.activation == 'sigmoid':
            return 1 / (1 + np.exp(-values))
        elif self.activation == 'tanh':
            return np.tanh(values)
        elif self.activation == 'softmax':
            e_x = np.exp(values - np.max(values, axis=-1, keepdims=True))
            return e_x / np.sum(e_x, axis=-1, keepdims=True)
        else:
            return values  # No activation (identity)

    def compute_derivative(self, values):
        if self.activation == 'relu':
            return (values > 0).astype(float)
        elif self.activation == 'sigmoid':
            sigmoid_output = self.apply_activation(values)
            return sigmoid_output * (1 - sigmoid_output)
        elif self.activation == 'tanh':
            tanh_output = self.apply_activation(values)
            return 1 - tanh_output**2
        elif self.activation == 'softmax':
            softmax_output = self.apply_activation(values)
            return softmax_output * (1 - softmax_output)  # Note: This derivative might not be used often for softmax
        else:
            return np.ones_like(values)  # Derivative of the identity function is 1

    def forward(self, input_matrix):
        values = np.dot(input_matrix, self.weight_matrix) + self.bias
        return self.apply_activation(values)

In [22]:
class Model:

    #to intiallize the model
    def __init__(self) -> None:
        
        inputNumber = 3 # input nodes
        self.numberOfLayers = 3 #number of hidden layer and output layer

        self.listOfHiddenLayers = []
        self.inLayerObj = inputLayer(inputNumber)

        for i in range(self.numberOfLayers):
            number_of_input = int(input('number of input: '))
            numberOfNeurons = int(input('number of neurons: '))
            activation = input('Enter the activation funtion: ')
            hidden_layer_obj = layers(number_of_input,numberOfNeurons,activation)

            self.listOfHiddenLayers.append(hidden_layer_obj)
            
            if i == self.numberOfLayers-1:
                self.numberOfLabels = numberOfNeurons

    def pridict(self,data,ForTraining = False):

        arr = self.inLayerObj.use(data)
        
        for layer in self.listOfHiddenLayers:
            arr = layer.forward(arr)

        if ForTraining:
            return arr

        pridiction_value = -1
        pridiction = None

        for i,obj in enumerate(arr[0]):
            if pridiction_value < obj:
                pridiction = {'label' : i, 'confidence' : obj}
        
        return pridiction
    

    def view_weights(self):
        for layer in self.listOfHiddenLayers:
            print(f'weights \n - {layer.weight_matrix}')
            print(f'bias - {layer.bias}')

    #backpropagation 
    def train(self,data,label):
        
        pridiction = self.pridict(data,ForTraining = True)
        reqArr =np.array([0 for i in range(self.numberOfLabels)])
        reqArr[label] = 1
        costFuntion = sum((pridiction - reqArr)**2)
        
        # print(reqArr)
        # print(costFuntion)
        # print(pridiction)

        pridiction = pridiction - reqArr

        for layers in self.listOfHiddenLayers[-1]:
            gradient = np.multiply(pridiction,layers.compute_derivative(pridiction))

        print(gradient)  
        

        


In [60]:
wig1 = np.array([[-0.80377147, -0.63344107],
                 [0.43278832, -0.02537794],
                 [-0.71144554, 0.79602224]])
wig2 = np.array([[ 0.30313998,-0.651056],
                 [ 0.11990958, -0.68028781]])
wig3 = np.array([[-0.13948543, -0.15244189 ,0.02360036],
                 [ 0.15260582 ,-0.41243941 ,0.62087499]])

b1 = np.array([-0.20960194,-0.86772309])
b2 = np.array([-0.04218223, 0.71097538])
b3 = np.array([-0.45757658, -0.6612067, 0.39908153])

testInputs = [3,2,'relu',wig1,b1,2,2,'relu',wig2,b2,2,3,'softmax',wig3,b3]

class ModelTest:

    #to intiallize the model
    def __init__(self) -> None:
        
        inputNumber = 3 # input nodes
        self.numberOfLayers = 3 #number of hidden layer and output layer

        self.listOfHiddenLayers = []
        self.inLayerObj = inputLayer(inputNumber)
        ind = 0
        for i in range(self.numberOfLayers):
            number_of_input = testInputs[ind]
            ind += 1
            numberOfNeurons = testInputs[ind]
            ind += 1
            activation = testInputs[ind]
            ind += 1
            w = testInputs[ind]
            ind += 1
            b = testInputs[ind]
            ind += 1
            hidden_layer_obj = layersT(number_of_input,numberOfNeurons,activation,w,b)

            self.listOfHiddenLayers.append(hidden_layer_obj)
            
            if i == self.numberOfLayers-1:
                self.numberOfLabels = numberOfNeurons

    def pridict(self,data,ForTraining = False):

        arr = self.inLayerObj.use(data)
        
        for layer in self.listOfHiddenLayers:
            arr = layer.forward(arr)

        if ForTraining:
            return arr

        pridiction_value = -1
        pridiction = None

        for i,obj in enumerate(arr[0]):
            if pridiction_value < obj:
                pridiction = {'label' : i, 'confidence' : obj}
        
        return pridiction
    

    def view_weights(self):
        for layer in self.listOfHiddenLayers:
            print(f'weights \n - {layer.weight_matrix}')
            print(f'bias - {layer.bias}')

    #backpropagation 
    def train(self,data,label):
        
        pridiction = self.pridict(data,ForTraining = True)
        reqArr =np.array([0 for i in range(self.numberOfLabels)])
        reqArr[label] = 1
        costFuntion = sum((pridiction - reqArr)**2)
        
        # print(reqArr)
        # print(costFuntion)
        # print(pridiction)

        pridiction = pridiction - reqArr

        for layers in self.listOfHiddenLayers[::-1]:
            gradient = np.multiply(pridiction,layers.compute_derivative(pridiction))
            print(gradient)  


In [61]:
nn = ModelTest()

'''
inputs here

input layer = input 3 (change in Model() if req)

hidden layer 1 = input - 3, nurons - 2
hidden layer 2 = input - 2, nurons - 2
hidden layer 2 = input - 2, nurons - 3 (output)
'''

'\ninputs here\n\ninput layer = input 3 (change in Model() if req)\n\nhidden layer 1 = input - 3, nurons - 2\nhidden layer 2 = input - 2, nurons - 2\nhidden layer 2 = input - 2, nurons - 3 (output)\n'

In [63]:
print(nn.view_weights())

weights 
 - [[-0.12610263  0.12528392]
 [ 0.31305123  0.94055467]
 [ 0.11155602  0.63653629]]
bias - [[ 0.22930223 -0.28140124]]
weights 
 - [[ 0.11912359  0.98243797]
 [-0.81085228  0.04559269]]
bias - [[-0.39662187 -0.13691448]]
weights 
 - [[-0.51862473  0.39332542 -0.99474809]
 [-0.67098109  0.77324672 -0.73810832]]
bias - [[-0.94974968  0.86715709 -0.20119708]]
None


In [62]:
data = np.array([1,2,3])
nn.train(data,0)

[[-0.08470812  0.21102066  0.01215333]]
[[-0.          0.90725851  0.06148264]]
[[-0.          0.90725851  0.06148264]]


In [52]:
sample_obj = layers(2,3,'softmax')

# a = sample_obj.compute_derivative(np.array([0.04001797, 0.02100264, 0.00303844]))
# a
nn.pridict([4,3,2])

{'label': 2, 'confidence': 0.15052100452377867}